bot:
  name: INNBot
  avatarPath: ./assets/bot-avatar.jpg
  gameName: testing
  description: >
                I'm INNBot, a Rogerian psychotherapist hired by the
                Imperial News Network. You can chat for a therapy session
                or tell me some commands. I'm an open source
                psychotherapist too, check my source out here: 
                https://github.com/ImperialNewsNetwork/inn-bot.
                To find the commands I can run, type !help.
  repositoryUrl: https://github.com/ImperialNewsNetwork/inn-bot
commands:
  prefix: '!'
  sources:
    - ./commands/baseradio.js
    - ./commands/chat.js
    - ./commands/community.js
    - ./commands/fun.js
    - ./commands/inn.js
    - ./commands/rsi-social.js
    - ./commands/rsi-tools.js
    - ./commands/starmap.js
    - ./commands/repository.js
    - ./commands/subreddit.js
  aliases:
    about:
      - info
    stats:
      - funds
      - citizens
      - uee
    issue:
      - bug
    thebase:
      - baseradio
  disabled:
    - echo
  disableAliases: false
  disableHelpCommand: false
  allowReplyToBots: false
  allowReplyToSelf: false
  allowReplyToEveryone: false
  allowReplyInPrivate: true
  helpCommandPadding: 10
chat:
  disable: false
subreddit:
  disable: false